### ISSUE TITLE
URxvt is not showing colours on one my computers

### ISSUE THREAD

**Issue by Hund** [BasioMeusPuga/twitchy#6] opened 2017-05-16 06:21 UTC
I have two computers with Arch Linux, both using URxvt with Zsh and they should have pretty much the same setups, because I'm boring. But only on of them shows colors correctly. The faulty ones shows only white, grey and red.

I currently have version `r123.cd04489-1` installed via AUR on the machine which is not working.

I'm not sure how to debug this? Colors is working just fine outside of Twitchy.

**Comment by BasioMeusPuga** [comment] 2017-05-16 06:42
Could you update to r133.478dddf-1 and tell me if this persists? Just `yaourt -S twitchy-git` should do it. git packages don't follow the whole -Syua thing.

**Comment by Hund** [comment] 2017-05-16 06:52
Ops, I copied the wrong string. I'm already using version `r133.478dddf-1`.

**Comment by BasioMeusPuga** [comment] 2017-05-16 07:02
My first thought was the color scheme on the faulty machine. I use white-on-black on konsole and the colors are basically in accordance with that. I tried using a solarized urxvt, and that does mess up the color scheme.
Could you try using a different `.Xdefaults`? Or maybe another terminal emulator for the purpose of debugging this?

**Comment by Hund** [comment] 2017-05-16 07:16
Oh, I forgot to mention it worked when I tried another terminal emulator. I have also tried various different colours in the config as well.

**Comment by BasioMeusPuga** [comment] 2017-05-16 08:02
I'm afraid I'm stumped. This combination of factors doesn't quite lend itself to pointing where the problem is. I'll experiment a bit with alternate escape codes. I'll update this if and when I find something.

**Comment by Hund** [comment] 2017-08-14 17:53
This is just so weird. I just tried the Gruvbox colorscheme with URxvt and it works then. But not with my Solarized colors? :|

Gruvbox: https://github.com/morhetz/gruvbox-contrib/blob/master/xresources/gruvbox-dark.xresources
My colors: https://github.com/Hund/dotfiles/blob/master/.Xresources

I even changed my config to directly use the HEX-values instead of the defined variables and it didn't work. It's super weird.

**Comment by Hund** [comment] 2017-08-15 20:14
I might have found someting. Solarized uses only 8 colours. It looks like Twitchy uses the colors 9-16. Changing it to use the first 8 colours should solve the issue. :)

![2017-08-15-221247_324x132_scrot](https://user-images.githubusercontent.com/320498/29334312-483507e0-8207-11e7-93df-038fdf300ca4.png)

**Comment by Hund** [comment] 2017-08-19 10:37
I tried to make a pull request, but GitHub doesnt allow me for some reason. I fixed the issue myself though, you can check it out here: https://github.com/Hund/twitchy/commit/abdaa533812a5724ff6bd21a53c6d9c2011e2870.

**Comment by BasioMeusPuga** [comment] 2017-08-19 11:31
Thank you for the changes. I sat down early this morning without coffee to fix that other bug, and I may have dozed off on my keyboard.

I've merged your commit into master (possibly by pressing buttons randomly).

**Comment by Hund** [comment] 2017-08-19 11:35
Haha! No coffee before work is dangerous. :)

**Comment by BasioMeusPuga** [comment] 2017-08-19 11:46
Are you sure this is working for you? I'm not getting any colors at all now. Except, of course, dark orange and dark cyan.

![screenshot_20170819_171342](https://user-images.githubusercontent.com/2138140/29486378-d632dd68-8501-11e7-9fab-5419bbc7dd97.png)

I really don't know much about terminal color schemes to make a reliable guess about what's happening. This could be a background color affecting everything bug.

I'm reverting the commit for now. But the issue is back to being open.

**Comment by Hund** [comment] 2017-08-19 12:56
Weird, it works for me.

**Comment by Hund** [comment] 2017-08-19 12:58
I would attach a image if GitHub worked... And I wouldn't double post if GitHub would allow me to edit my own comments... :|

**Comment by Hund** [comment] 2017-08-19 13:00
I give up. :P Here you go: http://imgur.com/a/7nIXD

**Comment by BasioMeusPuga** [comment] 2017-08-23 03:47
Twitch is shifting to v5 of their api in some time. While that would require only a partial rewrite, I've decided to do a more comprehensive redo of the entire program.
It should, in theory, make the curses version easier, and allow for more granular settings. At this point, I'd advise pressing F5 here eventually.

**Comment by Hund** [comment] 2017-08-23 03:52
Sound cool! :) F5?

**Closed as completed** 2017-08-23 03:52 UTC

**Comment by BasioMeusPuga** [comment] 2017-08-23 03:54
The refresh button? Between F4 and F6? That thing everyone on the planet does after a Game of Thrones episode on 'those' websites?

**Comment by Hund** [comment] 2017-08-23 03:57
Ah! Haha, I though that was F4. I've been using Vi-like web browsers for a very long time now.

**Comment by Hund** [comment] 2018-08-31 19:42
Any news about this? :) I would be nice to not have to manually change the source code all the time.
